### ISSUE TITLE
[J-05]: Backend CI 구축

### ISSUE THREAD

**Issue by joojae02** [boostcampwm2023/and01-SnapPoint#71]
## 작업 내용

```
on:
  pull_request:
    branches:
      - main

jobs:
  setup-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

  test:
    needs: setup-node
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Run test
        run: yarn test

  build:
    needs: setup-node
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
```
